# OrangeFox configuration.

OF_MAINTAINER := @phattylol

# Display.
OF_SCREEN_H := 2800
OF_STATUS_H := 180
OF_STATUS_INDENT_LEFT := 48
OF_STATUS_INDENT_RIGHT := 48
OF_HIDE_NOTCH := 1
OF_CLOCK_POS := 1
OF_ALLOW_DISABLE_NAVBAR := 0
OF_USE_GREEN_LED := 0

# A/B recovery.
OF_AB_DEVICE_WITH_RECOVERY_PARTITION := 1
OF_USE_LZ4_COMPRESSION := 1
OF_FORCE_PREBUILT_KERNEL := 1

# Dynamic partitions.
OF_ENABLE_LPTOOLS := 1
OF_ENABLE_ALL_PARTITION_TOOLS := 1

OF_DYNAMIC_FULL_SIZE := 9663676416

# Backup defaults.
OF_OPTIONS_LIST_NUM := 8
OF_QUICK_BACKUP_LIST := /boot;/data;
