DEVICE_PATH := device/nothing/Metroid

# Generated from proprietary-files.txt.
PRODUCT_COPY_FILES += \
    $(DEVICE_PATH)/proprietary/system/system/bin/servicemanager:$(TARGET_COPY_OUT_RECOVERY)/root/system/bin/servicemanager_a16 \
    $(DEVICE_PATH)/proprietary/system/system/lib64/libvintf.so:$(TARGET_COPY_OUT_RECOVERY)/root/system/lib64_a16/libvintf.so \
    $(DEVICE_PATH)/proprietary/system/system/lib64/libperfetto_c.so:$(TARGET_COPY_OUT_RECOVERY)/root/system/lib64_a16/libperfetto_c.so \
    $(DEVICE_PATH)/proprietary/system/system/lib64/libc++.so:$(TARGET_COPY_OUT_RECOVERY)/root/system/lib64_a16/libc++.so \
    $(DEVICE_PATH)/proprietary/system/system/lib64/android.hardware.security.keymint-V4-ndk.so:$(TARGET_COPY_OUT_RECOVERY)/root/system/lib64_a16/android.hardware.security.keymint-V3-ndk.so \
    $(DEVICE_PATH)/proprietary/system/system/lib64/android.hardware.security.keymint-V4-ndk.so:$(TARGET_COPY_OUT_RECOVERY)/root/system/lib64_a16/android.hardware.security.keymint-V4-ndk.so \
    $(DEVICE_PATH)/proprietary/system/system/lib64/android.hardware.security.secureclock-V1-ndk.so:$(TARGET_COPY_OUT_RECOVERY)/root/system/lib64_a16/android.hardware.security.secureclock-V1-ndk.so \
    $(DEVICE_PATH)/proprietary/system/system/lib64/android.system.keystore2-V5-ndk.so:$(TARGET_COPY_OUT_RECOVERY)/root/system/lib64_a16/android.system.keystore2-V4-ndk.so \
    $(DEVICE_PATH)/proprietary/system/system/etc/task_profiles.json:$(TARGET_COPY_OUT_RECOVERY)/root/system/etc/task_profiles.json \
    $(DEVICE_PATH)/proprietary/odm/etc/aac_richtap.config:$(TARGET_COPY_OUT_RECOVERY)/root/vendor/etc/aac_richtap.config \
    $(DEVICE_PATH)/proprietary/vendor/bin/qseecomd:$(TARGET_COPY_OUT_RECOVERY)/root/vendor/bin/qseecomd \
    $(DEVICE_PATH)/proprietary/vendor/etc/gpfspath_oem_config.xml:$(TARGET_COPY_OUT_RECOVERY)/root/vendor/etc/gpfspath_oem_config.xml \
    $(DEVICE_PATH)/proprietary/vendor/bin/hw/vendor.qti.hardware.qseecom@1.0-service:$(TARGET_COPY_OUT_RECOVERY)/root/vendor/bin/hw/vendor.qti.hardware.qseecom@1.0-service \
    $(DEVICE_PATH)/proprietary/vendor/bin/hw/android.hardware.security.keymint-service-qti:$(TARGET_COPY_OUT_RECOVERY)/root/vendor/bin/hw/android.hardware.security.keymint-service-qti \
    $(DEVICE_PATH)/proprietary/vendor/bin/hw/android.hardware.gatekeeper-service-qti:$(TARGET_COPY_OUT_RECOVERY)/root/vendor/bin/hw/android.hardware.gatekeeper-service-qti \
    $(DEVICE_PATH)/proprietary/vendor/bin/hw/android.hardware.security.keymint-service.strongbox-thales:$(TARGET_COPY_OUT_RECOVERY)/root/vendor/bin/hw/android.hardware.security.keymint-service.strongbox-thales \
    $(DEVICE_PATH)/proprietary/vendor/bin/hw/android.hardware.weaver-service.thales:$(TARGET_COPY_OUT_RECOVERY)/root/vendor/bin/hw/android.hardware.weaver-service.thales \
    $(DEVICE_PATH)/proprietary/vendor/bin/hw/android.hardware.secure_element-service.qti:$(TARGET_COPY_OUT_RECOVERY)/root/vendor/bin/hw/android.hardware.secure_element-service.qti \
    $(DEVICE_PATH)/proprietary/vendor/lib64/libcutils.so:$(TARGET_COPY_OUT_RECOVERY)/root/vendor/lib64/libcutils.so \
    $(DEVICE_PATH)/proprietary/vendor/lib64/libutils.so:$(TARGET_COPY_OUT_RECOVERY)/root/vendor/lib64/libutils.so \
    $(DEVICE_PATH)/proprietary/vendor/lib64/libQSEEComAPI.so:$(TARGET_COPY_OUT_RECOVERY)/root/vendor/lib64/libQSEEComAPI.so \
    $(DEVICE_PATH)/proprietary/vendor/lib64/libdrmfs.so:$(TARGET_COPY_OUT_RECOVERY)/root/vendor/lib64/libdrmfs.so \
    $(DEVICE_PATH)/proprietary/vendor/lib64/libminkdescriptor.so:$(TARGET_COPY_OUT_RECOVERY)/root/vendor/lib64/libminkdescriptor.so \
    $(DEVICE_PATH)/proprietary/vendor/lib64/libdmabufheap.so:$(TARGET_COPY_OUT_RECOVERY)/root/vendor/lib64/libdmabufheap.so \
    $(DEVICE_PATH)/proprietary/vendor/lib64/libc++.so:$(TARGET_COPY_OUT_RECOVERY)/root/vendor/lib64/libc++.so \
    $(DEVICE_PATH)/proprietary/vendor/lib64/libbase.so:$(TARGET_COPY_OUT_RECOVERY)/root/vendor/lib64/libbase.so \
    $(DEVICE_PATH)/proprietary/vendor/lib64/vendor.qti.hardware.qseecom-V1-ndk.so:$(TARGET_COPY_OUT_RECOVERY)/root/vendor/lib64/vendor.qti.hardware.qseecom-V1-ndk.so \
    $(DEVICE_PATH)/proprietary/vendor/lib64/hw/vendor.qti.hardware.qseecom@1.0-impl.so:$(TARGET_COPY_OUT_RECOVERY)/root/vendor/lib64/hw/vendor.qti.hardware.qseecom@1.0-impl.so \
    $(DEVICE_PATH)/proprietary/vendor/lib64/libhardware.so:$(TARGET_COPY_OUT_RECOVERY)/root/vendor/lib64/libhardware.so \
    $(DEVICE_PATH)/proprietary/vendor/lib64/libhidlbase.so:$(TARGET_COPY_OUT_RECOVERY)/root/vendor/lib64/libhidlbase.so \
    $(DEVICE_PATH)/proprietary/vendor/lib64/android.hardware.keymaster@4.0.so:$(TARGET_COPY_OUT_RECOVERY)/root/vendor/lib64/android.hardware.keymaster@4.0.so \
    $(DEVICE_PATH)/proprietary/vendor/lib64/libqtikeymint.so:$(TARGET_COPY_OUT_RECOVERY)/root/vendor/lib64/libqtikeymint.so \
    $(DEVICE_PATH)/proprietary/vendor/lib64/libcrypto.so:$(TARGET_COPY_OUT_RECOVERY)/root/vendor/lib64/libcrypto.so \
    $(DEVICE_PATH)/proprietary/vendor/lib64/android.hardware.security.keymint-V3-ndk.so:$(TARGET_COPY_OUT_RECOVERY)/root/vendor/lib64/android.hardware.security.keymint-V3-ndk.so \
    $(DEVICE_PATH)/proprietary/vendor/lib64/android.hardware.security.rkp-V3-ndk.so:$(TARGET_COPY_OUT_RECOVERY)/root/vendor/lib64/android.hardware.security.rkp-V3-ndk.so \
    $(DEVICE_PATH)/proprietary/vendor/lib64/android.hardware.security.secureclock-V1-ndk.so:$(TARGET_COPY_OUT_RECOVERY)/root/vendor/lib64/android.hardware.security.secureclock-V1-ndk.so \
    $(DEVICE_PATH)/proprietary/vendor/lib64/android.hardware.security.sharedsecret-V1-ndk.so:$(TARGET_COPY_OUT_RECOVERY)/root/vendor/lib64/android.hardware.security.sharedsecret-V1-ndk.so \
    $(DEVICE_PATH)/proprietary/vendor/lib64/hw/libqtigatekeeper.so:$(TARGET_COPY_OUT_RECOVERY)/root/vendor/lib64/hw/libqtigatekeeper.so \
    $(DEVICE_PATH)/proprietary/vendor/lib64/lib_android_keymaster_keymint_utils.so:$(TARGET_COPY_OUT_RECOVERY)/root/vendor/lib64/lib_android_keymaster_keymint_utils.so \
    $(DEVICE_PATH)/proprietary/vendor/lib64/libcppbor_external.so:$(TARGET_COPY_OUT_RECOVERY)/root/vendor/lib64/libcppbor_external.so \
    $(DEVICE_PATH)/proprietary/vendor/lib64/libkeymaster_portable.so:$(TARGET_COPY_OUT_RECOVERY)/root/vendor/lib64/libkeymaster_portable.so \
    $(DEVICE_PATH)/proprietary/vendor/lib64/libjc_keymint-thales.so:$(TARGET_COPY_OUT_RECOVERY)/root/vendor/lib64/libjc_keymint-thales.so \
    $(DEVICE_PATH)/proprietary/vendor/lib64/libjc_keymint_transport-thales.so:$(TARGET_COPY_OUT_RECOVERY)/root/vendor/lib64/libjc_keymint_transport-thales.so \
    $(DEVICE_PATH)/proprietary/vendor/lib64/android.se.omapi-V1-ndk.so:$(TARGET_COPY_OUT_RECOVERY)/root/vendor/lib64/android.se.omapi-V1-ndk.so \
    $(DEVICE_PATH)/proprietary/vendor/lib64/android.hardware.weaver-V2-ndk.so:$(TARGET_COPY_OUT_RECOVERY)/root/vendor/lib64/android.hardware.weaver-V2-ndk.so \
    $(DEVICE_PATH)/proprietary/vendor/lib64/ese_weaver_thales.so:$(TARGET_COPY_OUT_RECOVERY)/root/vendor/lib64/ese_weaver_thales.so \
    $(DEVICE_PATH)/proprietary/vendor/lib64/hw/libEseUtils.so:$(TARGET_COPY_OUT_RECOVERY)/root/vendor/lib64/hw/libEseUtils.so \
    $(DEVICE_PATH)/proprietary/vendor/lib64/libGPQeSE.so:$(TARGET_COPY_OUT_RECOVERY)/root/vendor/lib64/libGPQeSE.so \
    $(DEVICE_PATH)/proprietary/vendor/lib64/android.hardware.secure_element-V1-ndk.so:$(TARGET_COPY_OUT_RECOVERY)/root/vendor/lib64/android.hardware.secure_element-V1-ndk.so \
    $(DEVICE_PATH)/proprietary/vendor/lib64/libqcbor.so:$(TARGET_COPY_OUT_RECOVERY)/root/vendor/lib64/libqcbor.so \
    $(DEVICE_PATH)/proprietary/vendor/lib64/libdiag.so:$(TARGET_COPY_OUT_RECOVERY)/root/vendor/lib64/libdiag.so \
    $(DEVICE_PATH)/proprietary/vendor/lib64/libGPreqcancel.so:$(TARGET_COPY_OUT_RECOVERY)/root/vendor/lib64/libGPreqcancel.so \
    $(DEVICE_PATH)/proprietary/vendor/lib64/libGPreqcancel_svc.so:$(TARGET_COPY_OUT_RECOVERY)/root/vendor/lib64/libGPreqcancel_svc.so \
    $(DEVICE_PATH)/proprietary/vendor/lib64/libdrmtime.so:$(TARGET_COPY_OUT_RECOVERY)/root/vendor/lib64/libdrmtime.so \
    $(DEVICE_PATH)/proprietary/vendor/lib64/libgpt.so:$(TARGET_COPY_OUT_RECOVERY)/root/vendor/lib64/libgpt.so \
    $(DEVICE_PATH)/proprietary/vendor/lib64/libops.so:$(TARGET_COPY_OUT_RECOVERY)/root/vendor/lib64/libops.so \
    $(DEVICE_PATH)/proprietary/vendor/lib64/libqisl.so:$(TARGET_COPY_OUT_RECOVERY)/root/vendor/lib64/libqisl.so \
    $(DEVICE_PATH)/proprietary/vendor/lib64/librpmb.so:$(TARGET_COPY_OUT_RECOVERY)/root/vendor/lib64/librpmb.so \
    $(DEVICE_PATH)/proprietary/vendor/lib64/libspl.so:$(TARGET_COPY_OUT_RECOVERY)/root/vendor/lib64/libspl.so \
    $(DEVICE_PATH)/proprietary/vendor/lib64/libssd.so:$(TARGET_COPY_OUT_RECOVERY)/root/vendor/lib64/libssd.so \
    $(DEVICE_PATH)/proprietary/vendor/lib64/libtime_genoff.so:$(TARGET_COPY_OUT_RECOVERY)/root/vendor/lib64/libtime_genoff.so \
    $(DEVICE_PATH)/proprietary/vendor/lib64/libdrm.so:$(TARGET_COPY_OUT_RECOVERY)/root/vendor/lib64/libdrm.so \
    $(DEVICE_PATH)/proprietary/vendor/lib64/vendor.qti.hardware.display.config-V7-ndk.so:$(TARGET_COPY_OUT_RECOVERY)/root/vendor/lib64/vendor.qti.hardware.display.config-V7-ndk.so \
    $(DEVICE_PATH)/proprietary/vendor/lib64/libxml2.so:$(TARGET_COPY_OUT_RECOVERY)/root/vendor/lib64/libxml2.so \
    $(DEVICE_PATH)/proprietary/vendor/lib64/libseclog.so:$(TARGET_COPY_OUT_RECOVERY)/root/vendor/lib64/libseclog.so \
    $(DEVICE_PATH)/proprietary/vendor/lib64/android.hardware.common-V2-ndk.so:$(TARGET_COPY_OUT_RECOVERY)/root/vendor/lib64/android.hardware.common-V2-ndk.so \
    $(DEVICE_PATH)/proprietary/vendor/lib64/android.hardware.keymaster@3.0.so:$(TARGET_COPY_OUT_RECOVERY)/root/vendor/lib64/android.hardware.keymaster@3.0.so \
    $(DEVICE_PATH)/proprietary/vendor/lib64/libkeymasterdeviceutils.so:$(TARGET_COPY_OUT_RECOVERY)/root/vendor/lib64/libkeymasterdeviceutils.so \
    $(DEVICE_PATH)/proprietary/vendor/lib64/libkeymaster_messages.so:$(TARGET_COPY_OUT_RECOVERY)/root/vendor/lib64/libkeymaster_messages.so \
    $(DEVICE_PATH)/proprietary/vendor/lib64/android.hardware.keymaster@4.1.so:$(TARGET_COPY_OUT_RECOVERY)/root/vendor/lib64/android.hardware.keymaster@4.1.so \
    $(DEVICE_PATH)/proprietary/vendor/lib64/libkeymasterutils.so:$(TARGET_COPY_OUT_RECOVERY)/root/vendor/lib64/libkeymasterutils.so \
    $(DEVICE_PATH)/proprietary/vendor/lib64/android.hardware.gatekeeper-V1-ndk.so:$(TARGET_COPY_OUT_RECOVERY)/root/vendor/lib64/android.hardware.gatekeeper-V1-ndk.so \
    $(DEVICE_PATH)/proprietary/vendor/lib64/libgatekeeper.so:$(TARGET_COPY_OUT_RECOVERY)/root/vendor/lib64/libgatekeeper.so \
    $(DEVICE_PATH)/proprietary/vendor/lib64/libcppbor.so:$(TARGET_COPY_OUT_RECOVERY)/root/vendor/lib64/libcppbor.so \
    $(DEVICE_PATH)/proprietary/vendor/lib64/libcppcose_rkp.so:$(TARGET_COPY_OUT_RECOVERY)/root/vendor/lib64/libcppcose_rkp.so \
    $(DEVICE_PATH)/proprietary/vendor/lib64/libsoft_attestation_cert.so:$(TARGET_COPY_OUT_RECOVERY)/root/vendor/lib64/libsoft_attestation_cert.so \
    $(DEVICE_PATH)/proprietary/vendor/lib64/libbinder.so:$(TARGET_COPY_OUT_RECOVERY)/root/vendor/lib64/libbinder.so \
    $(DEVICE_PATH)/proprietary/vendor/lib64/libjc_weaver_transport.so:$(TARGET_COPY_OUT_RECOVERY)/root/vendor/lib64/libjc_weaver_transport.so \
    $(DEVICE_PATH)/proprietary/vendor/lib64/android.hardware.secure_element@1.0.so:$(TARGET_COPY_OUT_RECOVERY)/root/vendor/lib64/android.hardware.secure_element@1.0.so \
    $(DEVICE_PATH)/proprietary/vendor/lib64/libGPTEE_vendor.so:$(TARGET_COPY_OUT_RECOVERY)/root/vendor/lib64/libGPTEE_vendor.so \
    $(DEVICE_PATH)/proprietary/vendor/lib64/libion.so:$(TARGET_COPY_OUT_RECOVERY)/root/vendor/lib64/libion.so \
    $(DEVICE_PATH)/proprietary/vendor/lib64/android.hardware.secure_element@1.1.so:$(TARGET_COPY_OUT_RECOVERY)/root/vendor/lib64/android.hardware.secure_element@1.1.so \
    $(DEVICE_PATH)/proprietary/vendor/lib64/android.hardware.secure_element@1.2.so:$(TARGET_COPY_OUT_RECOVERY)/root/vendor/lib64/android.hardware.secure_element@1.2.so
